/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import UserInterface.Student.StudentGUI;
import Service.AuthService;
import DataModel.Student; 
import Util.DataManager; 
import Util.WindowUtils;
import java.awt.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author User
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private int failedAttempts = 0;
    private boolean isLocked = false;
    private Timer timer;
    
    public LoginGUI() {
        this.setResizable(false);
        initComponents();
        WindowUtils.centerWindow(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        title = new javax.swing.JLabel();
        usernameTitle = new javax.swing.JLabel();
        passwordTitle = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        userIdEnter = new javax.swing.JTextField();
        passwordEnter = new javax.swing.JPasswordField();
        errorMessageLabel = new javax.swing.JLabel();
        incorrectPassDisplay = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 188, 237));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ATCLogo.png"))); // NOI18N
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleMouseClicked(evt);
            }
        });

        usernameTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        usernameTitle.setText("UserID:");

        passwordTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        passwordTitle.setText("Password:");

        loginButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        userIdEnter.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        userIdEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdEnterActionPerformed(evt);
            }
        });

        passwordEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordEnterActionPerformed(evt);
            }
        });

        incorrectPassDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incorrectPassDisplayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdEnter)
                            .addComponent(passwordEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(incorrectPassDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginButton)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTitle)
                    .addComponent(userIdEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTitle)
                    .addComponent(passwordEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMessageLabel)
                    .addComponent(incorrectPassDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passwordTitle, userIdEnter, usernameTitle});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseClicked
     
    }//GEN-LAST:event_titleMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Check if it's locked
        if (isLocked) {
            JOptionPane.showMessageDialog(this, "Login is locked. Please wait.");
        return;
        }
        
        // Get inputId and inputPassword
        String inputId = userIdEnter.getText().trim();
        String inputPassword = new String(passwordEnter.getPassword());
        
        // Flag to track if login was succesful or not
        boolean credentialsValid = false;
        
        // Validate credentials
        if (!AuthService.foundId(inputId)){
            failedAttempts++;
            JOptionPane.showMessageDialog(this, "userID:"+"("+inputId+")"+"not found");
        }
        else if (AuthService.passwordIsCorrect(inputId, inputPassword)) {
            failedAttempts = 0;
            credentialsValid = true;
            JOptionPane.showMessageDialog(this, "Login Succesful!");
            
            // Open respective GUI based on user type
            switch (inputId.charAt(0)){
                
                 case 'S' -> {
                    // 1. Get DataManager for Student
                    DataManager<Student> studentManager = DataManager.of(Student.class);
                    // 2. Retrieve the logged-in Student object
                    Student loggedInStudent = studentManager.getRecordById(inputId);

                    if (loggedInStudent != null) {
                        // 3. Pass the Student object to StudentGUI's constructor
                        StudentGUI studentHomePage = new StudentGUI(loggedInStudent);
                        studentHomePage.pack();
                        WindowUtils.centerWindow(studentHomePage); // Use Window Utility method to center window
                        studentHomePage.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "Error: Student data not found for ID: " + inputId);
                    }
                } 
                
                case 'A' -> {
                    new UserInterface.Admin.AdminMainGUI(inputId).setVisible(true);
                }
                
                case 'R' -> {
                    new UserInterface.Receptionist.ReceptGUI(inputId).setVisible(true);  
               }


                
                case 'T' -> {
                    SwingUtilities.invokeLater(() -> new UserInterface.Tutor.TutorMainGUI(inputId).setVisible(true));
                }
                
                default -> {
                    JOptionPane.showMessageDialog(this, "Unknown user type.");
                    // No return here, as dispose() should still happen below
                }
            } // This brace correctly closes the 'switch' statement.
            
            // Close login form
            this.dispose();
            
        } // This brace correctly closes the 'else if' block.
        else { 
            failedAttempts++;
            JOptionPane.showMessageDialog(this, "Incorrect password. Attempt"+failedAttempts );
        }
            
        if (!credentialsValid && failedAttempts >= 3) {
            isLocked = true;
            loginButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Maximum failed attempt is 3 times. Please wait 5s and try again.");
            incorrectPassDisplay.setText("Login locked.");      
            incorrectPassDisplay.setForeground(Color.red);  
            
            // Start timer
            timer = new Timer(5000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    isLocked = false;
                    loginButton.setEnabled(true);
                    failedAttempts = 0;
                    incorrectPassDisplay.setText("");
                    JOptionPane.showMessageDialog(LoginGUI.this, "Login unlocked. Please try again.");
                    timer.stop();   
                }
            });
            timer.setRepeats(false);
            timer.start();    
        } 
    }//GEN-LAST:event_loginButtonActionPerformed

    private void userIdEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdEnterActionPerformed

    }//GEN-LAST:event_userIdEnterActionPerformed

    private void passwordEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordEnterActionPerformed

    }//GEN-LAST:event_passwordEnterActionPerformed

    private void incorrectPassDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incorrectPassDisplayMouseClicked
        
    }//GEN-LAST:event_incorrectPassDisplayMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel incorrectPassDisplay;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordEnter;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userIdEnter;
    private javax.swing.JLabel usernameTitle;
    // End of variables declaration//GEN-END:variables
}
