/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student;

import DataModel.Student; 
import DataModel.Subject; 
import Util.DataManager; 
import Service.StudentService; 
import javax.swing.*;
import java.util.List;

/**
 * GUI for students to request a change of subject.
 * This class extends JPanel and is designed to work with NetBeans's
 * auto-generated initComponents() method.
 */
public class ChangeSubjectGUI extends javax.swing.JPanel {
    
    private Student loggedInStudent;
    private StudentService studentService; // <--- Declare StudentService
    private DataManager<Subject> subjectManager;
    
    /**
     * No-argument constructor for ChangeSubjectGUI.
     * This is primarily for the IDE's design view or simple instantiation.
     * It initializes services and calls initComponents().
     */
    public ChangeSubjectGUI() {
        this.studentService = new StudentService();
        this.subjectManager = DataManager.of(Subject.class);
        initComponents(); // Call manual UI initialization
    }
    
     /**
     * Parameterized constructor for ChangeSubjectGUI.
     * This is the main constructor used in the application flow,
     * receiving the logged-in Student object.
     * @param student The logged-in Student object.
     */
    public ChangeSubjectGUI(Student student) {
        this(); // Call the no-argument constructor to initialize UI components
        this.loggedInStudent = student; // Set the specific student object
        populateSubjectComboBox(); // Populate subjects based on available data
        // No displayStudentInfo() as welcome label was removed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        selectNewSubjectLabel = new javax.swing.JLabel();
        insertCurrentSubjectLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        availableSubject = new javax.swing.JComboBox<>();
        reasonLabel = new javax.swing.JLabel();
        backHomeButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasonTextArea = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-stack.png"))); // NOI18N
        jLabel1.setText("Subject Change Request Form");

        jPanel2.setBackground(new java.awt.Color(235, 245, 238));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        selectNewSubjectLabel.setBackground(new java.awt.Color(255, 255, 204));
        selectNewSubjectLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        selectNewSubjectLabel.setForeground(new java.awt.Color(0, 0, 0));
        selectNewSubjectLabel.setText("Select New Subject:");

        insertCurrentSubjectLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        insertCurrentSubjectLabel.setForeground(new java.awt.Color(0, 0, 0));
        insertCurrentSubjectLabel.setText("N/A");

        subjectLabel.setBackground(new java.awt.Color(255, 255, 204));
        subjectLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        subjectLabel.setForeground(new java.awt.Color(0, 0, 0));
        subjectLabel.setText("Your Current Subjects:");

        availableSubject.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        availableSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableSubjectActionPerformed(evt);
            }
        });

        reasonLabel.setBackground(new java.awt.Color(255, 255, 204));
        reasonLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        reasonLabel.setForeground(new java.awt.Color(0, 0, 0));
        reasonLabel.setText("Reason:");

        backHomeButton.setText("Back");
        backHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeButtonActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        reasonTextArea.setColumns(20);
        reasonTextArea.setRows(5);
        jScrollPane1.setViewportView(reasonTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(reasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(subjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertCurrentSubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(selectNewSubjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(availableSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectLabel)
                    .addComponent(insertCurrentSubjectLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectNewSubjectLabel)
                    .addComponent(availableSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(reasonLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void availableSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableSubjectActionPerformed

    private void backHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeButtonActionPerformed
        // Close the current ChangeSubjectGUI's JFrame
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(ChangeSubjectGUI.this);
        if (currentFrame != null) {
            currentFrame.dispose();
        }
        
        // Open a new StudentGUI JFrame
        StudentGUI studentHome = new StudentGUI(loggedInStudent);
        studentHome.setVisible(true);
    }//GEN-LAST:event_backHomeButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        handleSubmitRequest();        
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * Populates the subject combo box with available subjects from DataManager.
     * This method should only be called when loggedInStudent is available.
     */
    private void populateSubjectComboBox() {
        // Create a new DefaultComboBoxModel to manage items
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        List<Subject> subjects = subjectManager.readFromFile();
        if (subjects.isEmpty()) {
            model.addElement("No subjects available"); // Add to model
            sendButton.setEnabled(false); // Disable submit if no subjects
        } else {
            for (Subject subject : subjects) {
                model.addElement(subject.getSubjectName()); // Add subjects to the model
            }
            sendButton.setEnabled(true);
        }
        availableSubject.setModel(model); // Set the model to the JComboBox
    }

    /**
     * Handles the submission of the subject change request.
     * Creates a StudentRequest object and saves it using StudentService.
     */
    private void handleSubmitRequest() {
        String selectedSubject = (String) availableSubject.getSelectedItem(); // Use availableSubject
        String notes = reasonTextArea.getText().trim(); // Use reasonTextArea

        if (selectedSubject == null || selectedSubject.equals("No subjects available")) {
            JOptionPane.showMessageDialog(this, "Please select a valid subject.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (notes.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Please provide a reason for the subject change.", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean success = studentService.submitSubjectChangeRequest(loggedInStudent, selectedSubject, notes);

        if (success) {
            JOptionPane.showMessageDialog(this, "Subject change request submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            reasonTextArea.setText(""); // Clear notes after submission
        } else {
            JOptionPane.showMessageDialog(this, "Failed to submit request. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> availableSubject;
    private javax.swing.JButton backHomeButton;
    private javax.swing.JLabel insertCurrentSubjectLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reasonLabel;
    private javax.swing.JTextArea reasonTextArea;
    private javax.swing.JLabel selectNewSubjectLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel subjectLabel;
    // End of variables declaration//GEN-END:variables
}
