/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student;

import DataModel.Student; 
import Service.StudentService; 
import Util.InputValidator;
import javax.swing.*; 
import java.awt.event.ActionListener;

/**
 * GUI for displaying and editing a student's profile.
 * This class is now a JPanel, designed to be embedded within a JFrame or other container.
 */
public class StudentProfileGUI extends javax.swing.JPanel { // Changed from JFrame to JPanel

    private Student loggedInStudent;
    private StudentService studentService;
    
    // Declare instance variables to store the initial state of text fields
    private String initialUsername;
    private String initialPassword;
    private String initialIcPassport;
    private String initialPhoneNumber;
    private String initialEmail;
    private String initialAddress;

    /**
     * Creates new form StudentProfileGUI.
     * @param student The Student object whose profile is to be displayed/edited.
     */
    public StudentProfileGUI(Student student) {
        this.loggedInStudent = student;
        this.studentService = new StudentService();

        initComponents(); 
        
        if (loggedInStudent != null) {
            studentIdText.setText(loggedInStudent.getId());
            usernameText.setText(loggedInStudent.getUsername());
            passwordText.setText(loggedInStudent.getPassword()); 
            enrollmentIdText.setText(loggedInStudent.getEnrollmentId());
            icPassportText.setText(loggedInStudent.getIcPassport());
            phoneNumberText.setText(loggedInStudent.getPhoneNumber());
            emailText.setText(loggedInStudent.getEmail());
            addressText.setText(loggedInStudent.getAddress());

            // Store initial values after setting text fields
            // These values will be used to check for unsaved changes
            initialUsername = loggedInStudent.getUsername();
            initialPassword = loggedInStudent.getPassword(); // This assumes password is not hashed on load
            initialIcPassport = loggedInStudent.getIcPassport();
            initialPhoneNumber = loggedInStudent.getPhoneNumber();
            initialEmail = loggedInStudent.getEmail();
            initialAddress = loggedInStudent.getAddress();
        }
        
        studentIdText.setEditable(false);
        enrollmentIdText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saveProfileButton = new javax.swing.JButton();
        backHomepageButton = new javax.swing.JButton();
        studentIdText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        enrollmentIdText = new javax.swing.JTextField();
        icPassportText = new javax.swing.JTextField();
        phoneNumberText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(235, 245, 238));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("StudentID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("EnrollmentID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("IC/Passport:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Phone Number:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Email:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Address: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password:");

        saveProfileButton.setText("Save");
        saveProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileButtonActionPerformed(evt);
            }
        });

        backHomepageButton.setText("Back");
        backHomepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomepageButtonActionPerformed(evt);
            }
        });

        studentIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdTextActionPerformed(evt);
            }
        });

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        passwordText.setText("jPasswordField1");

        enrollmentIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentIdTextActionPerformed(evt);
            }
        });

        addressText.setColumns(20);
        addressText.setRows(5);
        jScrollPane1.setViewportView(addressText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(icPassportText))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enrollmentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(studentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(passwordText)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backHomepageButton)
                .addGap(18, 18, 18)
                .addComponent(saveProfileButton)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(enrollmentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(icPassportText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backHomepageButton)
                    .addComponent(saveProfileButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jLabel1.setText("Student Profile Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileButtonActionPerformed
         String newUsername = usernameText.getText().trim();
        String newPassword = new String(passwordText.getPassword()).trim();
        String newIcPassport = icPassportText.getText().trim();
        String newPhoneNumber = phoneNumberText.getText().trim();
        String newEmail = emailText.getText().trim();
        String newAddress = addressText.getText().trim();

        // Basic validation
        if (newUsername.isEmpty() || newPassword.isEmpty() || newIcPassport.isEmpty() ||
            newPhoneNumber.isEmpty() || newEmail.isEmpty() || newAddress.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; // Stop further execution if validation fails
        }
        
        if (newUsername.isEmpty() || newPassword.isEmpty() || newIcPassport.isEmpty() ||
            newPhoneNumber.isEmpty() || newEmail.isEmpty() || newAddress.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validate email format using InputValidator
        if (!InputValidator.emailFormatIsValid(newEmail)) {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please use @gmail.com or @mail.com", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate phone number format (assuming a basic regex for 10 or 11 digits)
        if (!newPhoneNumber.matches("^\\d{10,11}$")) {
            JOptionPane.showMessageDialog(this, "Invalid phone number format. Please enter 10 or 11 digits.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Update the loggedInStudent object with new data
        loggedInStudent.setUsername(newUsername);
        loggedInStudent.setPassword(newPassword); // In a real application, hash passwords!
        loggedInStudent.setIcPassport(newIcPassport);
        loggedInStudent.setPhoneNumber(newPhoneNumber);
        loggedInStudent.setEmail(newEmail);
        loggedInStudent.setAddress(newAddress);

        // Call StudentService to save the updated student profile
        boolean success = studentService.updateStudentProfile(loggedInStudent);

        if (success) {
            JOptionPane.showMessageDialog(this, "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // After successful save, update the initial state to reflect the new saved data
            initialUsername = newUsername;
            initialPassword = newPassword;
            initialIcPassport = newIcPassport;
            initialPhoneNumber = newPhoneNumber;
            initialEmail = newEmail;
            initialAddress = newAddress;
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update profile. An error occurred.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_saveProfileButtonActionPerformed

    /**
     * Checks if there are any unsaved changes in the profile fields.
     * @return true if there are changes, false otherwise.
     */
    private boolean hasUnsavedChanges() {
        // Get current values from the text fields
        String currentUsername = usernameText.getText().trim();
        String currentPassword = new String(passwordText.getPassword()).trim();
        String currentIcPassport = icPassportText.getText().trim();
        String currentPhoneNumber = phoneNumberText.getText().trim();
        String currentEmail = emailText.getText().trim();
        String currentAddress = addressText.getText().trim();

        // Compare current values with the initial values
        return !currentUsername.equals(initialUsername) ||
               !currentPassword.equals(initialPassword) ||
               !currentIcPassport.equals(initialIcPassport) ||
               !currentPhoneNumber.equals(initialPhoneNumber) ||
               !currentEmail.equals(initialEmail) ||
               !currentAddress.equals(initialAddress);
    }
    
    private void backHomepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomepageButtonActionPerformed
        if (hasUnsavedChanges()) {
            int response = JOptionPane.showConfirmDialog(
                this,
                "You have unsaved changes. Are you sure you want to go back? All unsaved changes will be lost.",
                "Unsaved Changes",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            // If the user chooses NO, prevent going back
            if (response == JOptionPane.NO_OPTION) {
                return; 
            }
        }

        // User confirmed to proceed or no unsaved changes were present
        // Get the parent JFrame and dispose of it
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }
        // Open the StudentGUI (dashboard)
        StudentGUI studentDashboard = new StudentGUI(loggedInStudent);
        studentDashboard.setVisible(true);
    }//GEN-LAST:event_backHomepageButtonActionPerformed

    private void studentIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void enrollmentIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentIdTextActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressText;
    private javax.swing.JButton backHomepageButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField enrollmentIdText;
    private javax.swing.JTextField icPassportText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JButton saveProfileButton;
    private javax.swing.JTextField studentIdText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
