/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Receptionist;

import DataModel.Enrollment;
import DataModel.Payment;
import DataModel.StudentRequest;
import Util.DataManager;
import javax.swing.JOptionPane;
import java.util.function.Predicate; // ✅ REQUIRED for filterAndOverwrite
import java.util.stream.Collectors;
import DataModel.Student;

/**
 *
 * @author Naviin06
 */
public class DeleteStudentFromReceptionist extends javax.swing.JFrame {
private final String receptionistId;

    /**
     * Creates new form DeleteStudentFromReceptionist
     */
   public DeleteStudentFromReceptionist(String receptionistId) {
    this.receptionistId = receptionistId;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                   Delete Student");

        jLabel2.setText("Student ID:");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

   String studentId = txtStudentId.getText().trim();

    if (studentId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Student ID.");
        return;
    }

    // Step 1: Get Student record
    Student student = DataManager.of(Student.class).getRecordById(studentId);
    if (student == null) {
        JOptionPane.showMessageDialog(this, "Student not found.");
        return;
    }

    String enrollmentId = student.getEnrollmentId();

    // Step 2: Delete from Enrollment
    boolean foundInEnrollment = DataManager.of(Enrollment.class)
            .deleteById(enrollmentId);

    // Step 3: Delete from Payment
    boolean foundInPayment = DataManager.of(Payment.class)
            .deleteByCondition(p -> p.getStudentId().equalsIgnoreCase(studentId));

    // Step 4: Delete from StudentRequest
    boolean foundInRequest = DataManager.of(StudentRequest.class)
            .deleteByCondition(r -> r.getStudentId().equalsIgnoreCase(studentId));

    // Step 5: Delete from Student
    boolean foundInStudent = DataManager.of(Student.class)
            .deleteById(studentId);

    // Step 6: Notify
    if (foundInEnrollment || foundInPayment || foundInRequest || foundInStudent) {
        JOptionPane.showMessageDialog(this,
                "Student with ID " + studentId + " and related records have been deleted.");
    } else {
        JOptionPane.showMessageDialog(this,
                "No records found for Student ID: " + studentId);
    }

    txtStudentId.setText("");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
                                       
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
